X = Y = 1000

MAX_ANIMALS_PER_HELPER = 4
MAX_SIGHT_KM = 5
MAX_DISTANCE_KM = 1
MAX_FLOCK_SIZE = 4
ANIMAL_MOVE_PROBABILITY = 0.5
SCORE_FOR_BOTH_GENDERS_SAVED = 100
SCORE_FOR_EITHER_GENDER_SAVED = 1

MIN_T = 2016
MAX_T = MIN_T * 4
START_RAIN = 1008

ONE_BYTE = 1 << 8

# UI
GRASS_COLOR = (54, 228, 124)
DAMP_GRASS_COLOR = (34, 188, 154)
GRIDLINE_COLOR = (40, 40, 40)
BG_COLOR = (240, 240, 240)
ARK_COLOR = (120, 85, 33)
HELPER_COLOR = (40, 40, 60)
MALE_ANIMAL_COLOR = (10, 10, 240)
FEMALE_ANIMAL_COLOR = (240, 120, 120)

# Screen scaled for 13" MacBook (fits fully without clipping)
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 800

# Landscape (left side main grid)
LANDSCAPE_WIDTH = 820   # ~64% of width
LANDSCAPE_HEIGHT = 760  # height minus margins

# Minimap bottom-right
MAP_PX = 220

MAP_SPLIT = 10
SELECTED_INCREASE = 1.6

# Margins reduced for smaller UI
MARGIN_X = 10
MARGIN_Y = 20

LANDSCAPE_NORTH_PX = MARGIN_Y
LANDSCAPE_SOUTH_PX = MARGIN_Y + LANDSCAPE_HEIGHT
LANDSCAPE_WEST_PX = MARGIN_X
LANDSCAPE_EAST_PX = MARGIN_X + LANDSCAPE_WIDTH

NUM_GRID_LINES = min(20, X)

ARK_RADIUS = 25
HELPER_RADIUS = 8
ANIMAL_RADIUS = 12

HOVERED_HEIGHT = 260  # popup box fits screen
HOVERED_WIDTH = 360
HOVERED_MARGIN_X = 20

ALL_TURNS_PER_SECOND = [5, 20, 120]
DEFAULT_TURNS_PER_SECOND = ALL_TURNS_PER_SECOND[1]  # mid-speed default

INFO_HELPER_HEIGHT = 50  # sidebar rows smaller to fit more

# Precision
EPS = 0.01
